[2025-07-15T20:31:42.141+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-07-15T20:31:42.175+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: flight_model_training.train_and_log_model manual__2025-07-15T20:31:39.487156+00:00 [queued]>
[2025-07-15T20:31:42.185+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: flight_model_training.train_and_log_model manual__2025-07-15T20:31:39.487156+00:00 [queued]>
[2025-07-15T20:31:42.186+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2025-07-15T20:31:42.200+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): train_and_log_model> on 2025-07-15 20:31:39.487156+00:00
[2025-07-15T20:31:42.210+0000] {standard_task_runner.py:63} INFO - Started process 300 to run task
[2025-07-15T20:31:42.215+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'flight_model_training', 'train_and_log_model', 'manual__2025-07-15T20:31:39.487156+00:00', '--job-id', '2', '--raw', '--subdir', 'DAGS_FOLDER/flight_model_dag.py', '--cfg-path', '/tmp/tmpc98l5gnx']
[2025-07-15T20:31:42.228+0000] {standard_task_runner.py:91} INFO - Job 2: Subtask train_and_log_model
[2025-07-15T20:31:42.286+0000] {task_command.py:426} INFO - Running <TaskInstance: flight_model_training.train_and_log_model manual__2025-07-15T20:31:39.487156+00:00 [running]> on host 88a25da025bd
[2025-07-15T20:31:42.375+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='flight_model_training' AIRFLOW_CTX_TASK_ID='train_and_log_model' AIRFLOW_CTX_EXECUTION_DATE='2025-07-15T20:31:39.487156+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-07-15T20:31:39.487156+00:00'
[2025-07-15T20:31:42.377+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-07-15T20:32:28.259+0000] {logging_mixin.py:188} WARNING - 2025/07/15 20:32:28 WARNING mlflow.utils.git_utils: Failed to import Git (the Git executable is probably not on your PATH), so Git SHA is not available. Error: Failed to initialize: Bad git executable.
The git executable must be specified in one of the following ways:
    - be included in your $PATH
    - be set via $GIT_PYTHON_GIT_EXECUTABLE
    - explicitly set via git.refresh(<full-path-to-git-executable>)

All git commands will error until this is rectified.

This initial message can be silenced or aggravated in the future by setting the
$GIT_PYTHON_REFRESH environment variable. Use one of the following values:
    - quiet|q|silence|s|silent|none|n|0: for no message or exception
    - warn|w|warning|log|l|1: for a warning message (logging level CRITICAL, displayed by default)
    - error|e|exception|raise|r|2: for a raised exception

Example:
    export GIT_PYTHON_REFRESH=quiet
[2025-07-15T20:32:29.285+0000] {logging_mixin.py:188} WARNING - 2025/07/15 20:32:29 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.
[2025-07-15T20:32:34.277+0000] {logging_mixin.py:188} WARNING - 2025/07/15 20:32:34 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.
[2025-07-15T20:32:34.878+0000] {logging_mixin.py:188} INFO - üèÉ View run legendary-doe-30 at: http://mlflow:5000/#/experiments/474368820096796256/runs/e1cd17573b3544bda7057ab183d990f4
[2025-07-15T20:32:34.878+0000] {logging_mixin.py:188} INFO - üß™ View experiment at: http://mlflow:5000/#/experiments/474368820096796256
[2025-07-15T20:32:34.936+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-07-15T20:32:34.938+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/flight_model_dag.py", line 54, in train_model
    joblib.dump(model, '/opt/airflow/artifacts/flight_price_model.pkl')
  File "/home/airflow/.local/lib/python3.11/site-packages/joblib/numpy_pickle.py", line 599, in dump
    with open(filename, "wb") as f:
         ^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/opt/airflow/artifacts/flight_price_model.pkl'
[2025-07-15T20:32:34.951+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=flight_model_training, task_id=train_and_log_model, run_id=manual__2025-07-15T20:31:39.487156+00:00, execution_date=20250715T203139, start_date=20250715T203142, end_date=20250715T203234
[2025-07-15T20:32:34.964+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 2 for task train_and_log_model ([Errno 2] No such file or directory: '/opt/airflow/artifacts/flight_price_model.pkl'; 300)
[2025-07-15T20:32:35.006+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-07-15T20:32:35.019+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-07-15T20:32:35.023+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
